# Generated by Django 2.2 on 2020-12-19 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.TextField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('MAQUINISTA', 'MAQUINISTA'), ('1ER AYUDANTE', '1ER AYUDANTE'), ('2DO AYUDANTE', '2DO AYUDANTE'), ('3ER AYUDANTE', '3ER AYUDANTE')])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
